# RAG Configuration Settings
BEST_DISTANCE_THRESHOLD = 1.5
TOP_K_RETRIEVAL = 5
MAX_CHUNKS_RETURNED = 3
MIN_WORD_OVERLAP = 2
MAX_CONTEXT_TOKENS = 400
MIN_RESPONSE_LENGTH = 5  
MAX_RESPONSE_SENTENCES = 4